
package chess

const(
	PIECE_NULL byte = iota
	PIECE_SOLDIER  // 卒/兵
	PIECE_CANNON   // 炮
	PIECE_ROOK     // 车
	PIECE_SOWAR    // 马
	PIECE_MINISTER // 象/相
	PIECE_GUARD    // 士/仕
	PIECE_GENERAL  // 将/帅
)
const(
	TEAM_NULL byte = 0
	TEAM_BLK  byte = 1 << 6
	TEAM_RED  byte = 2 << 6
)

var stdmap [5][9]byte = [5][9]byte{
	{PIECE_ROOK   , PIECE_SOWAR , PIECE_MINISTER, PIECE_GUARD, PIECE_GENERAL, PIECE_GUARD, PIECE_MINISTER, PIECE_SOWAR , PIECE_ROOK},
	{PIECE_NULL   , PIECE_NULL  , PIECE_NULL    , PIECE_NULL , PIECE_NULL   , PIECE_NULL , PIECE_NULL    , PIECE_NULL  , PIECE_NULL},
	{PIECE_NULL   , PIECE_CANNON, PIECE_NULL    , PIECE_NULL , PIECE_NULL   , PIECE_NULL , PIECE_NULL    , PIECE_CANNON, PIECE_NULL},
	{PIECE_SOLDIER, PIECE_NULL  , PIECE_SOLDIER , PIECE_NULL , PIECE_SOLDIER, PIECE_NULL , PIECE_SOLDIER , PIECE_NULL  , PIECE_SOLDIER},
	{PIECE_NULL   , PIECE_NULL  , PIECE_NULL    , PIECE_NULL , PIECE_NULL   , PIECE_NULL , PIECE_NULL    , PIECE_NULL  , PIECE_NULL},
}
